# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('openId', models.CharField(max_length=50, unique=True, verbose_name='openId')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.IntegerField(default=1)),
                ('avatar', models.URLField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6848\u4f8b\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6848\u4f8b\u5185\u5bb9')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('doc', models.FileField(blank=True, upload_to='docs')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='law_type', to='weixin.LawCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.PositiveSmallIntegerField(choices=[(1, '\u5355\u9009'), (2, '\u591a\u9009'), (3, '\u5224\u65ad')], verbose_name='\u9898\u578b')),
                ('title', models.CharField(max_length=200, verbose_name='\u95ee\u9898')),
                ('option_A', models.CharField(blank=True, max_length=200, null=True, verbose_name='A')),
                ('option_B', models.CharField(blank=True, max_length=200, null=True, verbose_name='B')),
                ('option_C', models.CharField(blank=True, max_length=200, null=True, verbose_name='C')),
                ('option_D', models.CharField(blank=True, max_length=200, null=True, verbose_name='D')),
                ('option_E', models.CharField(blank=True, max_length=200, null=True, verbose_name='E')),
                ('answer', models.CharField(max_length=10, verbose_name='\u7b54\u6848')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
