# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawdocument',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='law', to='weixin.LawCategory'),
        ),
    ]
