# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_auto_20171202_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u95ee\u7b54\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u95ee\u7b54\u5185\u5bb9')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6545\u4e8b\u6807\u9898')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='weixin.Story')),
            ],
        ),
        migrations.DeleteModel(
            name='Publicity',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['types']},
        ),
        migrations.RemoveField(
            model_name='lawdocument',
            name='doc',
        ),
        migrations.AddField(
            model_name='lawdocument',
            name='content',
            field=models.TextField(default='', verbose_name='\u6cd5\u89c4\u5185\u5bb9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lawdocument',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u6587\u4ef6\u540d'),
        ),
    ]
