# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_auto_20171204_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='outlet',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
