# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0006_auto_20180121_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawdocument',
            name='doc',
            field=models.FileField(blank=True, upload_to='laws'),
        ),
    ]
